# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resizer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 350))
        MainWindow.setMaximumSize(QtCore.QSize(650, 350))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("Qt")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 631, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.formLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.formLabel.setFont(font)
        self.formLabel.setTextFormat(QtCore.Qt.PlainText)
        self.formLabel.setObjectName("formLabel")
        self.gridLayout.addWidget(self.formLabel, 0, 0, 1, 1)
        self.ratioLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.ratioLabel.setFont(font)
        self.ratioLabel.setObjectName("ratioLabel")
        self.gridLayout.addWidget(self.ratioLabel, 1, 0, 1, 1)
        self.constantRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.constantRadio.setFont(font)
        self.constantRadio.setChecked(True)
        self.constantRadio.setObjectName("constantRadio")
        self.GroupRatio = QtWidgets.QButtonGroup(MainWindow)
        self.GroupRatio.setObjectName("GroupRatio")
        self.GroupRatio.addButton(self.constantRadio)
        self.gridLayout.addWidget(self.constantRadio, 1, 1, 1, 1)
        self.variableRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.variableRadio.setFont(font)
        self.variableRadio.setObjectName("variableRadio")
        self.GroupRatio.addButton(self.variableRadio)
        self.gridLayout.addWidget(self.variableRadio, 1, 2, 1, 2)
        self.heightLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.heightLabel.setFont(font)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 2, 2, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.outputLabel.setFont(font)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout.addWidget(self.outputLabel, 4, 0, 1, 1)
        self.widthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widthEdit.setFont(font)
        self.widthEdit.setObjectName("widthEdit")
        self.gridLayout.addWidget(self.widthEdit, 2, 1, 1, 1)
        self.inputButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.inputButton.setObjectName("inputButton")
        self.gridLayout.addWidget(self.inputButton, 3, 4, 1, 1)
        self.heightEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.heightEdit.setFont(font)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 2, 3, 1, 1)
        self.outputEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.outputEdit.setObjectName("outputEdit")
        self.gridLayout.addWidget(self.outputEdit, 4, 1, 1, 3)
        self.resizeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        self.resizeButton.setFont(font)
        self.resizeButton.setObjectName("resizeButton")
        self.gridLayout.addWidget(self.resizeButton, 5, 1, 1, 3)
        self.inputLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.inputLabel.setFont(font)
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout.addWidget(self.inputLabel, 3, 0, 1, 1)
        self.inputEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inputEdit.setObjectName("inputEdit")
        self.gridLayout.addWidget(self.inputEdit, 3, 1, 1, 3)
        self.outputButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.outputButton.setObjectName("outputButton")
        self.gridLayout.addWidget(self.outputButton, 4, 4, 1, 1)
        self.widthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.widthLabel.setFont(font)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout.addWidget(self.widthLabel, 2, 0, 1, 1)
        self.folderRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.folderRadio.setFont(font)
        self.folderRadio.setChecked(True)
        self.folderRadio.setObjectName("folderRadio")
        self.GroupForm = QtWidgets.QButtonGroup(MainWindow)
        self.GroupForm.setObjectName("GroupForm")
        self.GroupForm.addButton(self.folderRadio)
        self.gridLayout.addWidget(self.folderRadio, 0, 1, 1, 1)
        self.fileRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.fileRadio.setFont(font)
        self.fileRadio.setObjectName("fileRadio")
        self.GroupForm.addButton(self.fileRadio)
        self.gridLayout.addWidget(self.fileRadio, 0, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ReSizer -0.2.0"))
        self.formLabel.setText(_translate("MainWindow", "<Form>"))
        self.ratioLabel.setText(_translate("MainWindow", "<Ratio>"))
        self.constantRadio.setText(_translate("MainWindow", "Constant"))
        self.variableRadio.setText(_translate("MainWindow", "Variable"))
        self.heightLabel.setText(_translate("MainWindow", "<Max Height>"))
        self.outputLabel.setText(_translate("MainWindow", "<Output Path>"))
        self.widthEdit.setText(_translate("MainWindow", "1920"))
        self.inputButton.setText(_translate("MainWindow", "..."))
        self.heightEdit.setText(_translate("MainWindow", "1080"))
        self.resizeButton.setText(_translate("MainWindow", "ReSize"))
        self.inputLabel.setText(_translate("MainWindow", "<Input Path>"))
        self.outputButton.setText(_translate("MainWindow", "..."))
        self.widthLabel.setText(_translate("MainWindow", "<Max Width>"))
        self.folderRadio.setText(_translate("MainWindow", "Folder"))
        self.fileRadio.setText(_translate("MainWindow", "File"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

